'use client'


import { useState, useContext } from "react";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { UserState } from "./types";
import { UserContext, SetUserContext } from "./context/userContext";
import "./globals.css";


const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const [userState, setUserState] = useState<UserState | null>(null)

    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <UserContext.Provider value={userState}>
                <SetUserContext.Provider value={setUserState}>
                    {children}
                </SetUserContext.Provider>
            </UserContext.Provider>
        </body>
        </html>
    );
}
